name: slgtformer
channels:
  - pytorch
  - nvidia
  - conda-forge
  - pyg
dependencies:
  - python=3.8
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - pyg
  - pytorch-scatter
  - wandb
  - pip
  - pip:
    - timm
    - einops